spring:
  application:
    name: hungry-belly-backend
  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
supabase:
  bucketName: ${BUCKET_NAME}
  accessKey: ${ACCESS_BUCKET_KEY}
  secretKey: ${SECRET_BUCKET_KEY}
  regionName: ${REGION_NAME}
  endpointUrl: ${S3_ENDPOINT}
  serviceRoleKey: ${SERVICE_ROLE_KEY}
  endpointSignUrl: ${SIGN_ENDPOINT}
